name: roomie_app
description: Aplicación móvil para búsqueda de roomies
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Estado y navegación
  provider: ^6.1.0
  go_router: ^13.0.0

  # Backend y autenticación
  supabase_flutter: ^2.0.0

  # Geolocalización y mapas
  geolocator: ^11.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geocoding: ^2.1.1

  # Utilidades
  image_picker: ^1.0.7
  cached_network_image: ^3.3.0
  intl: ^0.19.0
  uuid: ^4.2.1
  font_awesome_flutter: ^10.7.0

  # Animaciones
  flutter_animate: ^4.3.0

  # Stripe
  flutter_stripe: ^10.1.0
  http: ^1.2.0

  url_launcher: ^6.2.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  video_player: ^2.10.1
  chewie: ^1.13.0
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
